version: '3'
services:
  app:
    container_name: csgobroadcast
    image: ghcr.io/french-csgo/csgo-broadcast:latest
    volumes:
      - bin_data:/app/bin
    restart: always
    ports:
      - '8181:8181'
    env_file:
      - .env
    networks:
      - app-network

  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  bin_data:
  caddy_data:
  caddy_config:
