version: '3'
services:
  app:
    container_name: csgobroadcast
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8181:8181'
    environment:
      - NODE_ENV=development
    command: npm run start:dev